name: CI

on: push

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Type check
        run: pnpm typecheck

      - name: Code style (Prettier)
        run: pnpm lint

      - name: Lint (ESLint)
        run: pnpm lint:eslint

      - name: Build test
        run: pnpm build
